### ISSUE TITLE
cannot tag people as reviewers of pr until they accept invitation for collaborators

### ISSUE THREAD

**Issue by seanyang0813** [lob/intern-interviews#105]
Do I just wait for all four invitation to go through and then tag them or is there a different way to grant edit access?

**Comment by cortezd334** [comment]
I was wondering the same thing, have they accepted your invitation yet?

**Comment by rohanporeddy** [comment]
Even I'm waiting for the acceptance of the invitation. have they accepted yours?

**Comment by metalsheep** [comment]
Hi everyone, the tagging step was part of an early version of review workflow we were using and isn't necessary - https://github.com/lob/intern-interviews/pull/107 drops the instructions from the readme & you don't add us as "reviewers".

As long as you added us as collaborators & dropped a link to your PR in your application form, we will be able to find the code and conduct the review.
